web/home/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
   
    #首页 
    url(r'^$',views.index,name='index'),
    # 列表页
    url(r'^list/(?P<tid>[0-9]+)',views.list,name='list'),
    # 详情页
    url(r'^info/(?P<gid>[0-9]+)$',views.info,name='info'),
    # 注册
    url(r'^register/$',views.register,name='register'),
    # 登录
    url(r'^login/$',views.login,name='login'),
    # 退出登录
    url(r'^loginout/$',views.loginout,name='loginout'),

    # 购物车
    # 加入购物车
    url(r'^cart/add/$',views.cartadd,name='cartadd'),
    # 购物车列表
    url(r'^cart/list/$',views.cartlist,name='cartlist'),
    # 清空购物车
    url(r'^cart/clear/$',views.cartclear,name='cartclear'),
    # 修改购物车数量
    url(r'^cart/edit/$',views.cartedit,name='cartedit'),
    # 删除购物车商品
    url(r'^cart/del/$',views.cartdel,name='cartdel'),

    # 下单
    # 订单确认
    url(r'^order/confirm/$',views.orderconfirm,name='orderconfirm'),
    # 生成订单
    url(r'^order/create/$',views.ordercreate,name='ordercreate'),

    # 付款
    url(r'^order/buy/$',views.orderbuy,name='orderbuy'),

    # 我的订单
    url(r'^myorder/$',views.myorder,name='myorder'),
    # 我的个人中心
    url(r'^member/$',views.member,name='member'),
    # 地址修改
    url(r'^addressedit/$',views.addressedit,name='addressedit'),
    url(r'^addressupdate/$',views.addressupdate,name='addressupdate'),
    # 个人信息修改
    url(r'^edit/(?P<tid>[0-9]+)$',views.edit,name='edit'),
    # 个人信息更新
    url(r'^update/$',views.update,name='update'),
  
    

    
]

web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^admin/', include('myadmin.urls')),
    url(r'^', include('home.urls')),
    url(r'^ueditor/', include('ueditor.urls')),
]

web/home/models.py
from django.db import models

# Create your models here.

web/myadmin/models.py
from django.db import models

# Create your models here.
# 会员模型
class Users(models.Model):
    username=models.CharField(max_length=50)
    password=models.CharField(max_length=77)
    email=models.CharField(max_length=100,null=True)
    phone=models.CharField(max_length=11,null=True)
    sex=models.CharField(max_length=1,null=True)
    age=models.IntegerField(null=True)
    picurl=models.CharField(max_length=100,default='/static/pics/default/default.jpg')
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

# 商品分类模型
class types(models.Model):
    """docstring for ClassName"""
    name=models.CharField(max_length=50)
    pid=models.IntegerField()
    path=models.CharField(max_length=50)
    
# 商品模型

class Goods(models.Model):
    # 商品所属分类
    typeid = models.ForeignKey(to="types", to_field="id")
    # 商品标题
    title = models.CharField(max_length=255)
    # 商品价格
    price = models.DecimalField(max_digits=8, decimal_places=2)
    # 商品库存
    storage = models.IntegerField()
    # 商品图片
    pic = models.CharField(max_length=50)
    # 商品详情
    info = models.TextField()
    # 购买数量
    num  =  models.IntegerField(default=0)
    # 点击次数
    clicknum =  models.IntegerField(default=0)
    # 商品状态 1：新品、2：热销、3：下架
    status = models.IntegerField(default=1)
    # 商品添加时间
    addtime = models.DateTimeField(auto_now_add=True)

# 会员收货地址 模型

class Address(models.Model):
    # 用户id
    uid = models.ForeignKey(to="Users", to_field="id")
    # 收货人
    aname = models.CharField(max_length=20)
    # 收货地址
    aads = models.CharField(max_length=255)
    # 收货电话
    aphone = models.CharField(max_length=11)
    # 是否为默认 1 默认,
    status = models.IntegerField(default=0)



# 订单表
class Order(models.Model):
    uid = models.ForeignKey('Users',to_field="id")
    address = models.ForeignKey('Address',to_field='id')
    totalprice = models.FloatField()
    totalnum = models.IntegerField()
    # 1 未付款 2已付款,待发货,3已发货,待收货,4已完成,5已取消
    status = models.IntegerField()
    addtime = models.DateTimeField(auto_now_add=True)

# 订单详情
class OrderInfo(models.Model):
    orderid = models.ForeignKey('Order',to_field="id")
    gid =  models.ForeignKey('Goods',to_field="id")
    num = models.IntegerField()
    price = models.FloatField()

web/home/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from myadmin.models import Users,types,Goods,Address,Order,OrderInfo
from django.contrib.auth.hashers import make_password, check_password
# Create your views here.




def gettype():
    # 获取所有的二级分类
    data=types.objects.exclude(pid=0)
    return data

def index(request):
    data=types.objects.filter(pid=0)
    for x in data:
        x.sub=types.objects.filter(pid=x.id)
        for v in x.sub:
            v.sub=Goods.objects.filter(typeid=v.id)[:6]

    context={'typelist':gettype(),'navlist':data}
    return render(request,'home/index.html',context)



def login(request):
    if request.method=='GET':

        return render(request,'home/login.html')
    elif request.method=='POST':
        if request.POST['code'].lower() != request.session['verifycode'].lower():
            return HttpResponse('<script>alert("验证码错误");location.href="/login/"</script>')
        ob=Users.objects.filter(username=request.POST['username'])
        if ob:
            ob=ob[0]
            if check_password(request.POST['password'],ob.password):

                request.session['VipUser']={'name':ob.username,'pic':ob.picurl,'uid':ob.id}
                return HttpResponse('<script>alert("登录成功");location.href="/"</script>')
        return HttpResponse('<script>alert("用户名或密码错误");location.href="/login/"</script>')





def loginout(request):
    del request.session['VipUser']

    return HttpResponse('<script>location.href="/"</script>')


def register(request):

    # 判断当前请求的方式
    if request.method=='GET':
        return render(request,'home/register.html')
    elif request.method=='POST':
    # 执行注册
    # 判断用户是否存在
        res = Users.objects.filter(username=request.POST['username']).exists()
        if res:
            return HttpResponse('<script>alert("用户名已存在");location.href="/register"</script>')
    # 把用户信息存储到session
        else:
            ob=Users()
            print(ob)
            ob.username=request.POST['username']
            ob.password=make_password(request.POST['password'],None,'pbkdf2_sha256')
            ob.save()
            return HttpResponse('<script>alert("注册成功");location.href="/login/"</script>')

    # return render(request,'home/register.html')



def list(request,tid):
    # {'name':'服装','sub':[{'name':'男装'},{'name':'女装'}],'goods':[{},{},{},{}]}
    # 根据id获取当前分类的信息
    tod=types.objects.get(id=tid)
    if tod.pid==0:
        # 顶级分类
        data=tod
        # 获取子类
        data.sub=types.objects.filter(pid=tod.id)
        ids=[]
        for x in data.sub:
            ids.append(x.id)
        data.goods=Goods.objects.filter(typeid__in=ids)
    else:
        # 先获取父级对象
        data=types.objects.get(id=tod.pid)
        # 获取当前子类的商品信息
        data.goods=Goods.objects.filter(typeid=tod.id)
        # 获取所有的同级信息,包括当前类
        data.sub=types.objects.filter(pid=tod.pid)
        # 给data数据追加了一个obj对象
        data.obj=tod
    context={'typelist':gettype(),'data':data}
    return render(request,'home/list.html',context)



def info(request,gid):
    ginfo=Goods.objects.get(id=gid)
    context={'typelist':gettype(),'ginfo':ginfo}
    return render(request,'home/info.html',context)
    

# 加入购物车
def cartadd(request):
    try:
        # 接收商品id
        gid = request.GET['gid']
        # 加入购物车的数量
        num = int(request.GET['num'])

        # 获取购物车数据
        data = request.session.get('cart',{})
        
        # 判断商品是否已经存在与购物车中
        # {1:{},2:{}}
        if gid in data:
            # 如果已经存在,找到商品,修改数量
            data[gid]['num'] += num
        else:
            # 获取商品信息
            goods = Goods.objects.get(id=gid)
            # 把新的商品信息,追加到data数据中
            data[gid] = {'id':goods.id,'title':goods.title,'price':str(goods.price),'pic':goods.pic,'num':num}

        # 加入到session {1:{},2:{}}
        request.session['cart'] = data
        print(request.session['cart'])


        return JsonResponse({'code':0,'msg':'加入购物车成功'})
    # return HttpResponse('<script>alert("加入购物车成功");location.href="home/cartlist.html"</script>')
    except:
        return JsonResponse({'code':1,'msg':'加入购物车失败'})


# 购物车列表
def cartlist(request):


    context = {'typelist':gettype()}
    return render(request,'home/cartlist.html',context)


# 清空购物车
def cartclear(request):

    request.session['cart'] = {}

    return HttpResponse('<script>location.href="/cart/list/"</script>')


def cartedit(request):
    gid=request.GET.get('gid')
    num=int(request.GET.get('num'))
    data=request.session['cart']
    data[gid]['num']=num
    request.session['cart']=data
    return HttpResponse('<script>location.href="/cart/list/"</script>')

def cartdel(request):
    gid=request.GET['gid']
    data=request.session['cart']
    del data[gid]
    request.session['cart']=data
    return HttpResponse('aa')

# 确认订单
def orderconfirm(request):
    # print(request.GET['ids'])
    # print(request.session['cart'])
    # for i in request.session:
    #     print(request.session[i])
    # return HttpResponse('aa')

    if request.method == 'GET':

        # 获取用户选择的商品
        ids = request.GET['ids'].split(',')

        
        # 从session中读取购物车信息
        cartdata = request.session['cart']
        orderdata = {}

        for x in cartdata:
            if x in ids:
                orderdata[x] = cartdata[x]

        # 把用户选择购买的商品存入session
        request.session['order'] = orderdata

        # 需要让用户确认收货地址 获取当前用户的所有地址信息
        address = Address.objects.filter(uid=request.session['VipUser']['uid'])

        context = {'typelist':gettype(),'address':address}
        return render(request,'home/orderconfirm.html',context)

    elif request.method == 'POST':

        # 执行地址的添加
        ob = Address()
        ob.uid = Users.objects.get(id=request.session['VipUser']['uid'])
        ob.aname = request.POST['aname']
        ob.aphone = request.POST['aphone']
        ob.aads = request.POST['aads']

        # 状态修改
        s = request.POST.get('status',0)
        # 判断当前如果设置为默认值,
        if s == '1':
            # 把其它的地址修改状态 0 
            obs = Address.objects.filter(status=1)
            for x in obs:
                x.status = 0
                x.save()

        ob.status = s
        ob.save()
        return HttpResponse('<script>alert("地址添加成功");location.href="/order/confirm/?ids='+request.GET['ids']+'"</script>')


# 生成订单
def ordercreate(request):

    # 在session获取订单数据
    data = request.session['order']
    totalprice = 0
    totalnum = 0

    for x in data:
        n = float(data[x]['price']) * data[x]['num']
        totalprice += n
        totalnum += data[x]['num']


    # 创建订单
    order = Order()
    order.uid = Users.objects.get(id=request.session['VipUser']['uid'])
    order.address = Address.objects.get(id=request.POST['addressid'])
    order.totalprice = totalprice
    order.totalnum = totalnum
    order.status = 1
    order.save()
    
    # 读取购物车数据
    cart = request.session['cart']

    # 创建订单详情
    for x in data:
        orderinfo  = OrderInfo()
        # 订单号
        orderinfo.orderid = order
        # 获取当前购买的商品对象
        goods = Goods.objects.get(id=x)

        orderinfo.gid = goods
        orderinfo.num = data[x]['num']
        orderinfo.price = data[x]['price']
        orderinfo.save()
        # 清楚购物车的商品数据
        del cart[x]

        # 修改商品的购买数量
        goods.num +=  data[x]['num']
        goods.storage -= data[x]['num']
        goods.save()

        
    # 清空session中的订单数据
    request.session['order'] = {}
    # 更新购物车
    request.session['cart']= cart

    # 跳转到付款页面
    return HttpResponse('<script>alert("订单创建成功,请立即支付");location.href="/order/buy/?orderid='+str(order.id)+'"</script>')



# 付款页面
def orderbuy(request):
    orderid = request.GET.get('orderid',None)
    if orderid:
        # 通过订单id获取订单信息,并展示
        order = Order.objects.get(id=orderid)
        context = {'order':order}
        return render(request,'home/buy.html',context)


# 我的订单
def myorder(request):

    # 获取当前登录用户的所有订单信息
    orders = Order.objects.filter(uid=request.session['VipUser']['uid'])

    context = {'orders':orders}
    return render(request,'home/myorder.html',context)

# 我的个人中心
def member(request):
    
    if request.method == 'GET':  
        ob=Users.objects.get(id=request.session['VipUser']['uid'])
        orders = Order.objects.filter(uid=request.session['VipUser']['uid'])
        address = Address.objects.filter(uid=request.session['VipUser']['uid'])
        context={'myuser':ob,'orders':orders,'address':address}
        return render(request,'home/member.html',context)
    elif request.method == "POST":

        address= Address()
        address.uid = Users.objects.get(id=request.session['VipUser']['uid'])
        address.aname = request.POST['aname']
        address.aphone = request.POST['aphone']
        address.aads = request.POST['aads']
        address.save()
        return HttpResponse('<script>alert("添加地址成功");location.href="/member/"</script>')


 #个人信息修改   
def edit(request,tid):
    ob=Users.objects.get(id=tid)
    # print(ob)
    context={'uinfo':ob}
    # return HttpResponse('aa')
    return render(request,'home/edit.html',context)
# 个人信息修改
def update(request):
    # print(request.session['VipUser']['name'])
    try:
        
      
        ob=Users.objects.get(id=request.POST['id'])
        ob.username=request.POST.get('username')
        ob.email=request.POST.get('email')
        ob.phone=request.POST.get('phone')
        ob.age=request.POST.get('age')
        ob.sex=request.POST.get('sex')
        if request.FILES.get('pic'):
            if ob.picurl != '/static/pics/default/default.jpg':
                import os
                os.remove('.'+ob.picurl)
                ob.picurl=uploads(request)

        ob.save()
        print(request.session['VipUser']['name'])
        usersesion=request.session['VipUser']
        
        usersesion['name']=ob.username
        request.session['VipUser']=usersesion

web/templates/home/buy.html
{% extends 'home/public/base.html' %}

{% block css %}

<link rel="stylesheet" type="text/css" href="/static/home/public/css/cart.css">
<link rel="stylesheet" type="text/css" href="/static/home/public/css/cart-app.css">

{% endblock %}


{% block mbx %}
<div class="navbar-left">
    <ol class="breadcrumb">
        <li >购物车</li>
        <li >确认订单</li>
        <li class="active">在线支付</li>
        <li>完成 </li>
    </ol>
</div>

{% endblock %}

{% block con %}
<br><br><br><br><br>
<div class="mainbody cart">
    <div class="container">
    

        请为你的订单支付:<br>
        <p>订单号:{{ order.id }}</p>
        <p>订单总价:{{ order.totalprice }}</p>
    </div>
</div>

<div class="navbar-right">
    <a class="mz-btn success" href="{% url 'myorder' %}" >查看我的订单</a>
</div>
{% endblock %}

web/templates/home/cartlist.html
{% extends 'home/public/base.html' %}

{% block css %}

<link rel="stylesheet" type="text/css" href="/static/home/public/css/cart.css">
<link rel="stylesheet" type="text/css" href="/static/home/public/css/cart-app.css">

{% endblock %}


{% block mbx %}
<div class="navbar-left">
    <ol class="breadcrumb">
        <li class="active">购物车</li>
        <li>确认订单</li>
        <li>在线支付</li>
        <li>完成 </li>
    </ol>
</div>

{% endblock %}

{% block con %}
<br><br><br><br>
<div class="mainbody cart">
        <div class="container">
            <!-- 购物车详情头 -->
            <table class="cart-header">
                <tbody>
                    <tr>
                        <td class="cart-col-select col-md-3 col-xs-3 col-sm-3">
                            <div class="cart-select-all JSelectAll">
                                <div class="mz-checkbox"></div>
                                <span class="cart-select-title">全选</span>
                            </div>
                        </td>
                        <td class="cart-col-name col-md-3 hidden-xs hidden-sm">商品</td>
                        <td class="cart-col-price col-md-2 hidden-xs hidden-sm">单价(元)</td>
                        <td class="cart-col-number col-md-2 hidden-xs hidden-sm">数量</td>
                        <td class="cart-col-total col-md-1 hidden-xs hidden-sm">小计(元)</td>
                        <td class="cart-col-ctrl col-md-1 hidden-xs hidden-sm">操作</td>
                    </tr>
                </tbody>
            </table><!-- 购物车详情头 E-->
            
            <!-- 购物清单信息列表 -->
            <div class="cart-merchant-list">
                <div class="cart-merchant">
                    <table class="cart-merchant-body">
                        <tbody>
                        {% for v in request.session.cart.values %}
                            <tr class="cart-product" id="pro5">
                                <td class="cart-col-select col-md-3 col-xs-4 col-sm-4">  
                                    <div class="mz-checkbox " gid='{{ v.id }}'></div> 
                                    <a href="meilanx.html" class="cart-product-link" target="_blank">
                                        <img src="{{ v.pic }}" class="cart-product-img" alt="魅蓝 X">
                                    </a>
                                </td>
                                <td class="cart-col-name col-md-3 col-xs-8 col-sm-8">
                                    <a href="meilanx.html" class="cart-product-link" target="_blank">
                                      <p>{{ v.title }}</p>
                                    </a>
                                    
                                </td>
                                <td class="cart-col-price col-md-2 hidden-xs hidden-sm">
                                    <p>
                                        <span class="cart-product-price">{{ v.price }}</span>
                                    </p>
                                </td>
                                <td class="cart-col-number col-md-2 hidden-xs hidden-sm">
                                    <div class="cart-product-number-adder">
                                        <p class="cart-product-number-max show"></p>
                                        <div class="mz-adder cartnum" gid='{{ v.id }}'>
                                            <button class="mz-adder-subtract disabled"></button>
                                            <div class="mz-adder-num"><input class="mz-adder-input" value="{{ v.num }}" type="text"></div>
                                            <button class="mz-adder-add"></button>
                                        </div>
                                    </div>
                                </td>


                                {% load pagetag %}
                                <td class="cart-col-total col-md-1 hidden-xs hidden-sm">
                                    <span class="cart-product-price total">{%  cheng v.num v.price  %}</span>
                                </td>
                                <td class="cart-col-ctrl col-md-1 hidden-xs hidden-sm">
                                    <div class="cart-product-remove" gid='{{ v.id }}'>
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div><!-- 购物清单信息列表 E-->
        </div>
        <!-- 结算详情 -->
        <div class="cart-footer" id="cartFooter">
            <div class="container">
               <div class="cart-footer-left col-md-6 col-xs-4 col-sm-4">
                   <div class="cart-select-all JSelectAll" data-mdesc="全选按钮" data-mtype="store_cart_all">
                        <div class="mz-checkbox"></div>
                        <span class="cart-select-title">全选</span>
                   </div>
                   <!-- <span class="cart-remove-selected" id="removeSelected">删除选中的商品</span> -->
                   <span class="cart-footer-count">
                        共
                        <span class="cart-footer-num" id="totalCount">5</span>
                        件商品
                   </span>
                    <a href="{% url 'cartclear' %}" class="mz-btn btn-danger">清空购物车</a>
                </div>
                <div class="cart-footer-right col-md-5 col-md-offset-1 col-sm-offset-2 col-xs-8 col-sm-6">
                    <span class="cart-footer-sum">
                        <span class="cart-footer-text">已优惠</span>
                        <span class="cart-footer-num red" id="totalDiscount">0.00</span>
                        <span class="cart-footer-text">元， 合计(不含运费)：</span>
                        <span class="cart-footer-total" id="totalPrice">00.00</span>
                    </span>
                    <div class="mz-btn success" id="cartSubmit">去结算</div>
                </div>
            </div>
        </div><!-- 结算详情 E-->
    </div>

{% endblock %}


{% block js %}
<script type="text/javascript">
    //回顶部
    backTop();
    //全选
    allSelect();
    //商品数量加减
    cartAddMin();
</script>

<script type="text/javascript">
    // 商品加减绑定单击事件
    $('.cartnum button').click(function(){
        gid = $(this).parents('.cartnum').attr('gid')
        num = $(this).parents('.cartnum').find('input').val()

        $.get('{% url "cartedit" %}',{gid:gid,num:num},function(data){
            location.href=location.href;
        })

    })
    $('.cart-product-remove').click(function(){
        gid=$(this).attr('gid')
        // alert(gid)
        $.get("{% url 'cartdel' %}",{gid:gid})
    })
    // function totalPrice(){
    //     var total=0
    //     var ids=[]
    //     $('.cart-merchant-body .checked').each(function(){
    //         alert('11')
    //         p=$(this).parents('tr').find('.total').text()
    //         ids.push($(this).attr('gid'))
    //         alert(ids)
    //     })
    //     $('#totalPrice').text(total)
    //     return ids
    // }
    // $('#cartSubmit').click(function(){
    //     ids=totalPrice()
    //     if(ids.length==0){
    //         alert('请选择要购买的商品')
    //     }else{
    //         location.href='/order/confirm/?ids='+ids.join(',')
    //     }
    // })
    $('#cartSubmit').click(function(){
        // alert('11')
        ids = totalPrice()
        // alert('22')
        if(ids.length == 0){
            alert('请选择要购买的商品')
        }else{
            location.href="/order/confirm/?ids="+ids.join(',')
        }
    })


    // 总数计算
    function totalPrice(){
        var total = 0
        var ids = []
        // alert('33')

        // 获取已经选择元素
        // $('.cart-merchant-body .checked').parents('tr').find('.total').text()
        $('.cart-merchant-body .checked').each(function(){
            // alert('44')
            
            p = $(this).parents('tr').find('.total').text()
            // alert(p)
            // total += Number(p)
            ids.push($(this).attr('gid'))
            // alert(ids)

        })

        $('#totalPrice').text(total)
        return ids
    }


</script>


{% endblock %}

web/templates/home/myorder.html
{% extends 'home/public/base.html' %}


{% block css %}
<link rel="stylesheet" type="text/css" href="/static/home/public/css/order.css">
<link rel="stylesheet" type="text/css" href="/static/home/public/css/order-app.css">
{% endblock %}

{% block con %}
<div class="mainbody order">
    <div class="container">
        <!-- 面包屑导航 -->
        <div class="crumbs col-xs-12 col-sm-12">
            <ol class="breadcrumb">
                <li class="hidden-xs hidden-sm"><a href="index.html">首页</a></li>
                <li class="hidden-xs hidden-sm"><a href="member.html">我的商城</a></li>
                <li class="active">我的订单</li>
            </ol>
        </div><!-- 面包屑导航 E-->
        
        <div class="main clearfix">
            <!-- 左侧导航 -->
            <div class="left-nav f-fl col-md-4 hidden-xs hidden-sm">
                <div class="nav-main">
                    <a href="javascript:;" class="type-title"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>订单中心</a>
                    <a href="order.html" class="ml active">我的订单</a>
                    <a href="#" class="ml ">我的回购单</a>
                    <a href="#" class="ml ">我的意外保</a>
                    <a href="javascript:;" class="type-title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>个人中心</a>
                    <a href="/#" class="ml ">地址管理</a>
                    <a href="#" class="ml ">我的收藏</a>
                    <a href="#" class="ml ">消息提醒</a>
                    <a href="#" class="ml ">建议反馈</a>
                </div>
            </div><!-- 左侧导航 E-->
            <!-- 右侧内容展示 -->
            <div class="right-content f-fr col-md-8 col-xs-12 col-sm-12">
                <div class="order-main">
                    <div class="type-tab-btn">
                        <a href="javascript:;" class="allOrder active col-20" data-type="-1">全部订单</a><i class="line hidden-xs hidden-sm">|</i>
                        <a class="waitPay col-20" href="javascript:;" data-type="0">待付款<span class="amount _actAmount"></span></a><i class="line hidden-xs hidden-sm">|</i>
                        <a class="waitDeliver col-20" href="javascript:;" data-type="1">待发货</a><i class="line hidden-xs hidden-sm">|</i>
                        <a class="hasDeliver col-20" href="javascript:;" data-type="2">已发货</a><i class="line hidden-xs hidden-sm">|</i>
                        <a class="other col-20" href="javascript:;" data-type="99">其他</a>
                    </div>
                    <div class="list-head hidden-xs hidden-sm">
                    <ul class="clearfix">
                        <li class="w50">
                            <select id="checkType" class="check-type">
                                <option value="0">近三个月的订单</option>
                                <option value="1">全部订单</option>
                            </select>
                            订单明细
                        </li>
                        <li class="w125">售后</li>
                        <li class="w125">金额</li>
                        <li class="w125">状态</li>
                        <li class="w125">操作</li>
                    </ul>
                    </div>
                    <div id="tableList" class="type-contain ui-load-container">
                        <div class="ui-load-content"><input id="unPayNum" value="0" type="hidden">
                            <table class="orderItem">
                                <tbody>

                                {% for v in orders %}
                                    <tr class="trHead hidden-xs hidden-sm">
                                        <td colspan="4" class="title clearfix">
                                          <div class="f-fl">下单时间：<span class="time">{{ v.addtime|date:'Y-m-d H:i:s'}}</span>订单号：<span class="orderNumber">51090244361541573081  {{ v.id }}</span>
                                          </div>
                                        </td>
                                    </tr>
                                    <tr class="list-box b-l b-r b-b">
                                        <td class="list b-r j-iamCart">
                                            <div class="cart-wrap j-CartWrap">
                                                <div class="shop j-shop j-amLight">
                                                    {% for vv in v.orderinfo_set.all %}
                                                    <div class="item b-t clearfix j-item j-iamMain">
                                                        <a class="productDetail nameWidth col-xs-4 col-sm-4" href="#" target="_blank">
                                                            <img src="{{ vv.gid.pic }}" class="f-fl">
                                                        </a>
                                                        <div class="describe f-fl col-xs-8 col-sm-8">
                                                            <div class="vertic clearfix">
                                                                <span class="clearfix">
                                                                    <a class="productDetail nameWidth" href="#" target="_blank">
                                                                    <i>{{ vv.gid.title }}</i> </a>
                                                                    <p>
                                                                    ￥{{ vv.price }}×{{ vv.num }}
                                                                    </p>
                                                                </span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    {% endfor %}

                                                </div>
                                            </div>
                                        </td>

                                        <td class="b-r w125 center price b-t hidden-xs hidden-sm">
                                            <div class="priceDiv">
                                                ￥ {{ v.totalprice }}
                                                
                                            </div>
                                        </td>
                                        <td class="b-r w125 center state b-t hidden-xs hidden-sm">
                                            <div class="stateDiv">
                                                {% if v.status == 1 %}
                                                   <div>未付款<br></div>
                                                {% elif v.status == 2%}
                                                   <div>待发货<br></div>
                                                {% elif v.status == 3%}
                                                   <div>待收货<br></div>
                                                {% elif v.status == 4%}
                                                   <div>待评价<br></div>
                                                {% elif v.status == 5%}
                                                   <div>已取消<br></div>
                                                {% endif %}
                                                  
                                            </div>
                                        </td>
                                        <td class="w125 center opreat b-t hidden-xs hidden-sm">
                                            <ul>
                                                <li class="more"><a href="#" target="_blank">查看详情</a></li>
                                            </ul>
                                        </td>
                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  
</div>

{% endblock %}